"""combine Movies and TVShows into one table Titles and add Reviews table with relationships

Revision ID: 0ae977f7b19d
Revises: 720f9bfc934d
Create Date: 2024-01-31 16:56:10.493254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae977f7b19d'
down_revision = '720f9bfc934d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.String(length=20), nullable=False),
    sa.Column('overview', sa.String(length=200), nullable=False),
    sa.Column('genre_ids', sa.PickleType(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('movie_or_tv', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movies')
    op.drop_table('tv_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_shows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=20), nullable=False),
    sa.Column('overview', sa.VARCHAR(length=200), nullable=False),
    sa.Column('genre_ids', sa.BLOB(), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=20), nullable=False),
    sa.Column('overview', sa.VARCHAR(length=200), nullable=False),
    sa.Column('genre_ids', sa.BLOB(), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reviews')
    op.drop_table('titles')
    # ### end Alembic commands ###
