"""change realese date to datetime

Revision ID: 7ff24843f76a
Revises: dc8434350617
Create Date: 2024-02-01 15:36:07.698430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff24843f76a'
down_revision = 'dc8434350617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
