"""add rating to the titles table

Revision ID: dc8434350617
Revises: 0ae977f7b19d
Create Date: 2024-01-31 17:47:16.255233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8434350617'
down_revision = '0ae977f7b19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
